server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:://127.0.0.1:3306/next-blog
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 3000
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static