server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next-blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1000
      idle-timeout: 60000
      max-lifetime: 10
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    #设置thymeleaf页面缓存失效
    cache: false
    #thymeleaf模版前缀，默认值,可选项
    prefix: classpath:/templates/
    #thymeleaf模版后缀，默认值,可选项
    suffix: .html
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  config: classpath:log4j2.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
upload:
  uploadAuthorImg: "/upload/author_img/"
  fileUploadDic: "/upload/article/"